In [11]:
import pandas as pd
import matplotlib.pyplot as plt

In [12]:
df = pd.read_csv("Taxi_Trips_-_2022_20260216.csv")
df.head()

,Trip ID,Taxi ID,Trip Start Timestamp,Trip End Timestamp,Trip Seconds,Trip Miles,Pickup Census Tract,Dropoff Census Tract,Pickup Community Area,Dropoff Community Area,...,Extras,Trip Total,Payment Type,Company,Pickup Centroid Latitude,Pickup Centroid Longitude,Pickup Centroid Location,Dropoff Centroid Latitude,Dropoff Centroid Longitude,Dropoff Centroid Location
0,f79b95d2f20cc77112c3d2f746f23ace1f3b35d7,db39bc53c7204111f0786edff94251c636dcce5fec8dbe...,02/14/2022 10:45:00 PM,02/14/2022 11:00:00 PM,960,0.4,NaN,NaN,56.0,59.0,...,$5.00,$25.00,Cash,Taxi Affiliation Services,41.792592,-87.769615,POINT (-87.7696154528 41.7925923603),41.829922,-87.672503,POINT (-87.6725026464 41.8299223039)
1,f85cfc1b84b572a83170074525fb2c4146a00c88,3d5fcccd2f2e4fb12eba0d94f8cdf657b20d405fece7c8...,02/14/2022 10:45:00 PM,02/14/2022 10:45:00 PM,0,0.0,1.703198e+10,1.703198e+10,76.0,76.0,...,$0.00,$3.25,Cash,Taxi Affiliation Services,41.979071,-87.903040,POINT (-87.9030396611 41.9790708201),41.979071,-87.903040,POINT (-87.9030396611 41.9790708201)
2,1ed7927861499b77cd52b3b0f89fb9e295345c39,cb3bd991c2f7932527ef9d5f341674dfba53745f25fe3e...,02/14/2022 10:45:00 PM,02/14/2022 10:45:00 PM,0,0.0,NaN,NaN,1.0,1.0,...,$0.00,$3.25,Cash,Blue Ribbon Taxi Association Inc.,42.009623,-87.670167,POINT (-87.6701668569 42.0096228806),42.009623,-87.670167,POINT (-87.6701668569 42.0096228806)
3,20a472710d72d661f1c811b7dd06b5719a80d280,8942c504d38b52d769ac1800e8c7dde070687626dcae14...,02/14/2022 10:45:00 PM,02/14/2022 11:15:00 PM,"1,980",0.5,NaN,NaN,2.0,8.0,...,$0.00,$29.00,Unknown,Taxi Affiliation Services,42.001571,-87.695013,POINT (-87.6950125892 42.001571027),41.899602,-87.633308,POINT (-87.6333080367 41.899602111)
4,1c8bb004ede21967e1fb817f9e2ab7b8ddf1855a,d96279b9f0d9e121dca78282e8ead29d8a7aa18dc89d78...,02/14/2022 10:45:00 PM,02/14/2022 10:45:00 PM,60,0.0,NaN,NaN,22.0,22.0,...,$0.00,$3.25,Cash,Taxi Affiliation Services,41.922761,-87.699155,POINT (-87.6991553432 41.9227606205),41.922761,-87.699155,POINT (-87.6991553432 41.9227606205)

In [13]:
print(df.columns)

Index(['Trip ID', 'Taxi ID', 'Trip Start Timestamp', 'Trip End Timestamp',
       'Trip Seconds', 'Trip Miles', 'Pickup Census Tract',
       'Dropoff Census Tract', 'Pickup Community Area',
       'Dropoff Community Area', 'Fare', 'Tips', 'Tolls', 'Extras',
       'Trip Total', 'Payment Type', 'Company', 'Pickup Centroid Latitude',
       'Pickup Centroid Longitude', 'Pickup Centroid Location',
       'Dropoff Centroid Latitude', 'Dropoff Centroid Longitude',
       'Dropoff Centroid  Location'],
      dtype='object')

In [14]:
distance_col = "Trip Miles"
fare_col = "Fare"   # change to "Trip Total" if you want total amount instead

In [15]:
distance_col = "Trip Miles"
fare_col = "Trip Total"

In [16]:
df[distance_col] = pd.to_numeric(df[distance_col], errors="coerce")
df[fare_col] = pd.to_numeric(df[fare_col], errors="coerce")

In [17]:
df_clean = df.dropna(subset=[distance_col, fare_col]).copy()

print("Original shape:", df.shape)
print("Cleaned shape:", df_clean.shape)

Original shape: (166705, 23)
Cleaned shape: (0, 23)

In [18]:
zero_distance_with_fare = df_clean[
    (df_clean[distance_col] == 0) & (df_clean[fare_col] > 0)
]

print("Rows where distance = 0 but fare > 0:", len(zero_distance_with_fare))
zero_distance_with_fare[[distance_col, fare_col]].head(10)

Rows where distance = 0 but fare > 0: 0

Empty DataFrame
Columns: [Trip Miles, Trip Total]
Index: []

In [19]:
zero_fare_with_distance = df_clean[
    (df_clean[distance_col] > 0) & (df_clean[fare_col] == 0)
]

print("Rows where fare = 0 but distance > 0:", len(zero_fare_with_distance))
zero_fare_with_distance[[distance_col, fare_col]].head(10)

Rows where fare = 0 but distance > 0: 0

Empty DataFrame
Columns: [Trip Miles, Trip Total]
Index: []

In [20]:
print("Summary")
print("-------")
print("0 distance, but fare > 0:", len(zero_distance_with_fare))
print("distance > 0, but 0 fare:", len(zero_fare_with_distance))

Summary
-------
0 distance, but fare > 0: 0
distance > 0, but 0 fare: 0